export const AGREGAR_FLAT = "AGREGAR_FLAT";
export const AGREGAR_FLAT_EXITO = "AGREGAR_FLAT_EXITO";
export const AGREGAR_FLAT_ERROR = "AGREGAR_FLAT_ERROR";

export const COMENZAR_DESCARGA_FLAT = "COMENZAR_DESCARGA_FLAT";
export const OBTENER_FLAT_EXITO = "OBTENER_FLAT_EXITO";
export const OBTENER_FLAT_ERROR = "OBTENER_FLAT_ERROR";

export const AGREGAR_USUARIO = "AGREGAR_USUARIO";
export const AGREGAR_USUARIO_EXITO = "AGREGAR_USUARIO_EXITO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_EXITO = "LOGIN_EXITO";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const ORDENAR_ALFA = "ORDENAR_ALFA";
export const ORDENAR_PRICE = "ORDENAR_PRICE";
